openSUSE/wicked

- extensions/hostname
Since the syslog service is not installed by default on openSUSE systems,
the outcome of `rcsyslog reload` should not impact setting a hostname via
this Wicked extension.
> extensions-hostname: return value to be based on outcome of hostname set

- src/fsm.c
In case of XML config file, when parent node (bridge) does not have <control> node specified we do not generate it for the child device either. Otherwise it is cloned.
Children of bond device have control node by default generated (STARTMODE=hotplug).
> xml: don't require parent's control node for cfg gener. (bsc#901517)

- src/ifevent.c
- src/iflist.c
- src/uevent.c
A device name provided in a event may be obsolete in the meantime
(renamed, event backlog), thus explicitly query and update it on
newlink and udev event before we emit wicked device events.
> events: query and update device name on events  (bug#904061)

- client/compat.c
- client/suse/compat-suse.c
- client/wicked-client.h
- dhcp4/dbus-api.c
- dhcp4/device.c
- dhcp4/dhcp.h
- dhcp4/protocol.c
- include/wicked/addrconf.h
- man/ifcfg-dhcp.5.in
- schema/addrconf.xml
- src/names.c
Handles parsing of rfc3004 formatted user-class
as well as non-standard but common string type.
> dhcp4: handle user-class option in config (bsc#909307)

- src/fsm.c
This change makes it easier to handle more fsm related timers (e.g. watermark timer).
> fsm: more generalized timer set/cancel functions

- src/fsm.c
wicked: br367: calling org.opensuse.Network.Bridge.deleteDevice()
wicked: ni_dbus_object_call_variant(/org/opensuse/Network/Interface/10, if=org.opensuse.Network.Bridge, method=deleteDevice)
wicked: br367: waiting for event in state device-ready
wicked: br367: state=device-ready want=device-down, wait-for=device-down
wicked: waiting for 1 devices to become ready (1 explicitly requested)
wicked: br367: state=device-ready want=device-down, wait-for=device-down
wicked: waiting for 1 devices to become ready (1 explicitly requested)
wicked: interface_state_change_signal: got signal deviceDelete from /org/opensuse/Network/Interface/10; event uuid=<>
wicked: br367: changed state device-ready -> device-down, resuming activity
wicked: br367: cancel worker's timeout
wicked: …
> Fsm: wait for ACK on device-delete transition

- client/compat.c
- client/ifcheck.c
- client/ifcheck.h
- client/ifstatus.c
- client/suse/compat-suse.c
- include/wicked/fsm.h
- include/wicked/netinfo.h
- man/Makefile.am
- man/ifcfg.5.in
- man/ifup.8.in
- src/client/client_state.c
- src/client/client_state.h
- src/dbus-objects/interface.c
- src/fsm.c
- src/ifconfig.c
- src/netdev.c
Initial handing of control/link-detection require-link and timeout flags
to continue setup without ready link (bsc#911562,bsc#914792).
> fsm: permit to continue setup without a ready link

- client/ifreload.c
This caused a segfault trying to parse the argument.
> ifreload: require argument in --timeout option

- src/ifconfig.c
- src/kernel.h
Initial dummy0[0] = if_nametoindex("dummy0") was not there
as it should be.
> dummy: fix handling of automatically created dummy0

- src/logging.c
Without options the pid is used, but syslog::stderr
resets it and syslog::stderr,pid was rejected...
> logging: add pid option to syslog log-target

- include/wicked/fsm.h
- nanny/nanny.c
- src/fsm.c
- src/wireless.c
Instead to add not yet ready devices to the normal fsm worker set, add them into a special
pending worker set to avoid confusions while resolving dependencies by name before or
while udev renames them and thus assign wrong config to devices (bsc#918662) and handle
related event race conditions (bsc#921218).
> fsm: fixes to use only ready devices by name and event races

- include/wicked/bonding.h
- schema/bonding.xml
- src/bonding.c
- src/ifconfig.c
> bonding: don't insist on active-backup mode when arp_validate=none  (boo#919573)

- client/ifreload.c
- src/fsm.c
In order to handle such a case properly we need:
- initial hierarchy build be non-destructive otherwise we delete the competing worker (e.g. two bridge workers: one is created, second is the replacement)
- next hierarchy rebuild after ifdown part of ifreload
- remove the <master>$name</master> from the <link/> node of the child's config.
> Ifreload: properly handle rename cases

- src/fsm-policy.c
Reject worker (or child) in the <match> check only when:
- device has been created for a given worker,
but it isn't ready.
- it's a config worker
This commit fixes ae67663af679414d2020437689d22cacefb5d92f.
> policy: fix to worker must be ready to satisfy match check

- client/ifup.c
- include/wicked/fsm.h
- schema/bridge.xml
- schema/infiniband.xml
- schema/macvlan.xml
- schema/ppp.xml
- schema/vlan.xml
- src/fsm.c
This is needed in order to catch and order sequence of FSM action steps properly for scenarios where a device has both master and lower device dependency. That it a bond0.21 vlan interface needs to wait for its lower bond0 interface to be at least in device-up state _and_ it has to wait till its master (e.g. lab21) interface is present to it can receive single second NEWLINK with both relationships set.
> fsm: use netif-reference shared flag as relation indicator in meta:require too

- src/teamd.c
On failure (e.g. teamd currently not running), the discover were
freeing team pointer on the device without proper reset, instead
of the local variable it allocated for the results, causing to
run into a segfault on a dangling pointer later.
> team: fix segfault on teamd discovery failure

- dhcp4/fsm.c
- dhcp4/protocol.c
RFC 6842 requires that servers MUST send back client-id as
sent by the client and that client MUST verify it, when it
receives it in server responses.
Some servers need a config option (e.g. echo-client-id on
recent ISC dhcp) to send client-id back.
> dhcp4: verify client-id if send back by the server

- etc/systemd/wicked.service.in
- etc/systemd/wickedd-auto4.service.in
- etc/systemd/wickedd-dhcp4.service.in
- etc/systemd/wickedd-dhcp6.service.in
- etc/systemd/wickedd-nanny.service.in
- etc/systemd/wickedd.service.in
Fixed to want nanny in wicked client (rcnetwork) service, added explicit before
wickedd-nanny ordering to wickedd service and changed to use wants instead
of wantedby install dependencies which are active for enabled services only.
> service: fixed wicked client and nanny dependencies (bsc#950333)

- autoip4/main.c
- client/tester.c
- dhcp4/main.c
- dhcp6/main.c
- src/appconfig.h
- src/ifevent.c
- src/iflist.c
- src/netinfo.c
- src/netinfo_priv.h
dhcp6 does not need IPv4 related state, dhcp4 and auto4 do not need IPv6.
> netconfig: do not refresh unrelated link details of address families

- src/ifconfig.c
- src/ovs.c
- src/ovs.h
This just avoids errors when the port is already in the db,
but does not trigger an enslave inside of openvswitch yet.
The remaining parts have to be addressed in openvswitch.
> ovs: use --may-exist option in add-port (bsc#951315)

- client/ifup.c
- client/nanny.c
- include/wicked/fsm.h
- nanny/device.c
- nanny/main.c
- nanny/nanny.c
- nanny/nanny.h
- nanny/policy.c
- src/client/ifconfig.h
- src/fsm-policy.c
Instead to create and kickstart or update policies (two step replace),
then try to enable managed devices, immediately replace policies and
schedule recheck to activate them to avoid a device detection race
condition, where the client creates/updates the policy, but skips to
activate it, because it doesn't know the device (ifindex) yet.
> ifup: replace policies to avoid a race (bsc#953107)

- wicked.spec.in
systemctl show makes a systemd query and does not work in
a chroot or when systemd is not available and using it in
RPM scripts breaks offline update. Replaced with readlink.
> rpm: do not use systemctl show in scripts (bsc#955778)

- include/wicked/fsm.h
- nanny/device.c
- nanny/nanny.c
- src/fsm-policy.c
- src/fsm.c
To handle late link / hotplugging, nanny were restarting device configuration
as the fsm were not handling down events in ifup run. In same combinations,
this were breaking dependencies/requirements of other devices e.g. vlan on
eth where eth is also port of a bridge and does not require link.
> fsm: hande events instead to workaround in nanny (bsc#955864)

- client/ifreload.c
- client/ifup.c
- include/wicked/fsm.h
- src/fsm.c
Since fsm check requirements are dynamic, we do not need to enforce any order of workers or policies being processed. Thus flatten functionality can be removed.
The fsm worker hierarchy loops should be checked earlier and on every hierarchy rebuild. That way we can always detect misconfiguration and fail affected workers.
> fsm: do not segfault on device hierarchy loops (bnc#959356)

- src/dbus-objects/misc.c
When receiving device addresses/routes status via dbus, clear the
old lists before applying new. In address case, it caused to wait
the full time in the client-side tentative address check, because
the the address with tentative flag were not replaced properly.
> ipv6: clear old address list before applying new

- src/fsm.c
- src/xml-reader.c
Added also a guard to the underlying xml node location
function to check node before accessing node->location.
> fsm: fixed wrong check causing segmentation fault

- man/wicked-config.5.in
Default is to use netlink messages, the
``
<bonding><ctl>sysfs</ctl></bonding>
``
in server.xml permits to use the old sysfs way.
> man: documented netlink vs sysfs bonding/ctl switch

- src/dhcp6/device.c
Some kernel forget to forward IPv6 RA flags via NEWLINK event
(boo#975020). Refresh ipv6 link info on prefix event also when
there is no request yet to workaround the missed NEWLINK event.
> dhcp6: refresh ipv6 link on each prefix event (boo#972471)

- include/wicked/util.h
- src/teamd.c
- src/util.c
This does not remove the allocation failure assert yet,
but permits to adopt the code to check the results.
> util: return a result in string utils

- wicked.spec.in
This are static service templates to start pppd, which do
not need any enable/disable or restart on wicked reinstall
as they do not use wicked binaries.
> spec: removed ppp service template macro calls (fate#317976)

- src/iflist.c
It were causing segmentation faults on recent kernels since header update in wicked 0.6.35.
> iflist: fixed macvlan link info data parsing

- autoip4/main.c
- client/tester.c
- dhcp4/main.c
- dhcp6/main.c
- src/ifconfig.c
- src/ifevent.c
- src/iflist.c
- src/kernel.c
- src/kernel.h
- src/netinfo_priv.h
All our kernel support routing policy rules since ages, but fail to start even
when rules are not used in the configuraion, is not the right error handling.
Also improved rtnetlink failure error messages and debug logging.
> rules: do not fail completely when kernel support is missed (bsc#981887)

- include/wicked/constants.h
- src/iflist.c
- src/names.c
Query if ovs device (kind or driver set to openvswitch) is a bridge using
ovs-vsctl br-exists first, then query ovs about the further bridge details.
> ovs: use generic ovs type until we can query ovs (bsc#982231)

- src/netdev.c
- src/update.c
Decouple to not leave orphaned system updater background jobs,
which blocked job processing, when a device object is deleted
and the reference through device, lease, update gets cleared.
> updater: fix orphaned bg jobs on device delete (bsc#1029133)

- src/fsm.c
Create full clone of config snippets we resolve and bind to method
args as the binding/resolving is modifying them. Clear namespace
attribute in resolved reference node so it does not confuse later.
This also fixes ifindex references as used by the iBFT extension.
> fsm: clone bound config and cleanup references (bsc#1030053)

- man/ifcfg.5.in
The directory name is 'scripts' instead of 'script' so fix that.
> man: ifcfg.5: Fix directory name for compatibility scripts

- src/dbus-objects/interface.c
- src/ifconfig.c
wicked should not supplement what drivers in kernel are capable. That
means, that if device is up, and is not capable set MTU on-fly, kernel
returns error. This is driver problem, not wicked and should just
print an error and continue.
Signed-off-by: Nikola Pajkovsky <npajkovsky@suse.cz>
> ifconfig: set MTU even if device is up (bsc#1059292)

- src/netinfo.c
When a master device is deleted, explicitly clear references
pointing to it on slaves instead to let it perform by further
event, which may arrive later than an attempt to enslave them
into a new, recreated master device (with same name).
> wickedd: explicitly unbind slaves on deletion (bsc#1061051)

- src/dbus-xml.c
This was breaking the build of wicked in Fedora, which does `-Werror=format-security` in the default build flags.
> Enforce formatting input as string

- src/dbus-objects/addrconf.c
I'm not sure how this call ever worked, since `dbus_set_error()` was missing necessary arguments to operate properly...
> Add missing DBUS_ERROR_FAILED error type to dbus_set_error() call

- wicked.pc.in
When wicked switched from `libnl1` to `libnl3` in 4591b86fda9e5b1e9383eb7e1ee0190ee57f8a1e, the required changes to `wicked.pc` were not made. This meant that the modules requested to link against `libwicked` by external applications were wrong and would lead to broken builds.
> Fix wicked pkgconfig file to request libnl3 instead of libnl1

- src/dbus-objects/misc.c
The schema contains only hwaddr properties with a minimal length of 6 bytes (ethernet);
sending empty hwaddr causes xml deserialization failure on optional properties (show-xml).
> dbus: omit zero-length hwaddr data properties

- client/main.c
This PR adds filtering functionality to the show-xml command, with the following behaviour:
- `wicked show-xml <ifname1> <ifname2>`: show xml *only* for `ifname1` and `ifname2`
- `wicked show-xml all`: show xml for all available network interfaces
- `wicked show-xml`: same as above, show all interfaces
This should address issue #735
> Fix show-xml filtering by interface name (issue #735,bsc#954758)

- src/ifconfig.c
The connected mode is optional for Target Channel Adapters (TCAs) acc. to RFC rfc4755,
so report failure to set it as (configuration) error, but do not fail the setup completely, same
with user-multicast option for consistency.
> ipoib: do not fail setup on mode or umcast set failure (bsc#1084462)

- client/compat.c
- client/suse/compat-suse.c
- client/suse/config/sysconfig.dhcp-wicked
- client/tester.c
- client/wicked-client.h
- dhcp4/dbus-api.c
- dhcp4/main.c
- man/ifcfg-dhcp.5.in
- schema/addrconf.xml
- src/dhcp4/device.c
- src/dhcp4/dhcp4.h
- src/dhcp4/protocol.c
- src/dhcp4/tester.c
- src/dhcp4/tester.h
This PR adds support for a new sysconfig option DHCLIENT_BROADCAST that, when set to "yes", will ask the DHCP server to send a broadcast response instead of a unicast one. 
Note that this is the default behaviour on Infiniband devices but is disabled otherwise. This PR basically adds the option to have this on non-infiniband devices too.
> dhcp4: add ifcfg option to request broadcast response from server

- client/suse/config/sysconfig.dhcp-wicked
- man/ifcfg-dhcp.5.in
This option was implemented a while ago but was not still documented in sysconfig/network/dhcp nor man pages.
> man: add missing documentation for DHCLIENT6_CLIENT_ID

- man/wicked-config.5.in
- src/dhcp6/device.c
- src/dhcp6/device.h
- src/dhcp6/dhcp6.h
- src/dhcp6/fsm.c
This PR fixes both RFC 3315 section 22.8 Preference option and improves wicked's own "weight" option implementation.
> dhcp6: Fix server preference and weight option behaviour

- client/suse/compat-suse.c
https://github.com/openSUSE/wicked/issues/756
> ifcfg: show unknown/invalid bootproto as error

- src/ethtool.c
e.g. tso has been splitted into several features and the
old STSO offload ioctl sets multiple features at once.
> ethtool: call offload ioctl if requested by offload name

- extensions/firewall
This PR changes the firewall extension to not get the default zone from firewall-cmd for the --change-interface, but rather pass a empty zone string; firewalld should interpret this empty string as "use default zone".
> firewall: do not assign default zone, but pass as is (bsc#1109147)

- client/suse/compat-suse.c
- src/wpa-supplicant.c
Fix for issue https://github.com/openSUSE/wicked/issues/777 to map eap auth method correctly when sending it to wpa-supplicant and to assume mschapv2 as PEAP auth when not specified in ifcfg config.
> wireless: fix eap peap auth mapping for wpa-supplicant (bsc#1026807)

- src/dhcp4/tester.c
- src/dhcp6/tester.c
sysconfig global default is to not request and update hostname,
but the wicked test dhcp[46] should show it by default.
> dhcp: request hostname/fqdn option in the tester (bsc#1118378)

- configure.ac
Can be disabled by running configure with `--disable-relro`.
Compare https://build.opensuse.org/request/show/657805
> link with full relro by default: binary hardening

- src/kernel.c
Pointed by valgrind.
```
Syscall param ioctl(SIOCETHTOOL) points to uninitialised byte(s)
==10768==    at 0x6637467: ioctl (in /lib64/libc-2.26.so)
==10768==    by 0x4EDE3F6: __ni_ioctl (kernel.c:66)
==10768==    by 0x4EDE799: __ni_ethtool (kernel.c:106)
==10768==    by 0x4ED4888: __ni_process_ifinfomsg_linktype (iflist.c:1149)
==10768==    by 0x4ED4888: __ni_process_ifinfomsg_linkinfo (iflist.c:1602)
==10768==    by 0x4ED4E34: __ni_netdev_process_newlink (iflist.c:1831)
==10768==    by 0x4EDA2BB: __ni_system_refresh_all (iflist.c:591)
==10768==    by 0x4EDA76E: __ni_system_refresh_interfaces (iflist.c:518)
==10768==    by 0x4EEBB4F: ni_global_state_handle (netinfo.c:480)
==10768==    by 0x402AA9: discover_state (main.c:334)
==10768==    by 0x402AA9: run_interface_server (main.c:277) …
```
> Init memory before use in ioctl

- src/config.c
A per device specified route-options and create-cid config options
where reset instead to inherit from global defaults, causing to not
consider them and to not send any dhcp4 routing options in requests
when other config (e.g. custom options) were defined per device.
> dhcp4: clone all wicked-config dhcp4 options (bsc#1132326)

- src/rfkill.c
This fixes broken Wifi support reported in:
https://bugzilla.suse.com/show_bug.cgi?id=1140117
Signed-off-by: Egbert Eich <eich@suse.com>
> rfkill: In switch statement check enum variable not constant

- etc/systemd/wickedd.service.in
This change moves the ExecStartPre call that was causing wickedd.service to timeout under some scenarios to a proper systemd dependency where the udev settle wait time doesn't count as wickedd.service start time
> systemd: change to depend on udev settle service (bsc#1136034,bsc#1132774)

- src/dhcp6/protocol.c
Lower the log level for "unexepected xid" messages in DHCPv6 replies from the server, as usually these mismatches between expected xid vs received xid happen in slow networks due to high latency and are _usually_ safe to ignore.
> dhcp6: lower unexpected xid messages to debug level

- autoip4/autoip.h
- autoip4/fsm.c
- include/wicked/socket.h
- include/wicked/wireless.h
- src/async-resolver.c
- src/capture.c
- src/dbus-objects/wireless.c
- src/dhcp4/device.c
- src/dhcp4/dhcp4.h
- src/dhcp4/fsm.c
- src/dhcp4/protocol.c
- src/dhcp6/device.c
- src/dhcp6/fsm.c
- src/dhcp6/lease.c
- src/dhcp6/protocol.c
- src/dhcp6/protocol.h
- src/leasefile.c
- src/leaseinfo.c
- src/lldp.c
- src/socket.c
- src/timer.c
- src/wireless.c
- src/wpa-supplicant.c
- src/wpa-supplicant.h
Fixes to use boot time for timers/timeouts and real time only in lease
files to not stuck in timers due to adjustments of the system time.
Consistently log dhcp xid and enabled to log dhcp6 timings line.
> time: use boot time for timer instead of real time (bsc#1129986)

- client/compat.c
- client/suse/compat-suse.c
- client/suse/config/sysconfig.dhcp-wicked
- client/wicked-client.h
- dhcp6/dbus-api.c
- schema/addrconf.xml
- src/dhcp6/device.c
- src/dhcp6/dhcp6.h
- src/dhcp6/protocol.c
Add an address-length aka DHCLIENT6_ADDRESS_LENGTH ifcfg option, which
permits to specify explicit prefix-length to use for the DHCPv6 address,
e.g. 64 to use address as 2001:db8::1/64 or 80 for 2001:db8::1/80.
When 0 or unspecified (default), prefix-length of the smallest on-link
prefix (highest /length number) in the IPv6 router advertisement matching
the address is used or 128 (see also rfc5942).
> dhcp6: do not default to a /64 address prefix-length (bsc#1132280)

- man/ifcfg-dhcp.5.in
Document new DHCLIENT6_ADDRESS_LENGTH setting in the man pages.
> man: document new address-length setting

- include/wicked/address.h
- src/address.c
- src/dhcp6/protocol.c
Do not create an implicit prefix (route) by adding an address with prefix
other than 128, even when we've received an on-link RA prefix.
> dhcp6: set the noprefixroute address option (bsc#1132280)

- include/wicked/ipv6.h
- src/dhcp6/device.c
- src/dhcp6/device.h
- src/dhcp6/dhcp6.h
- src/dhcp6/fsm.c
- src/dhcp6/protocol.c
- src/dhcp6/protocol.h
- src/dhcp6/tester.c
- src/iflist.c
- src/ipv6.c
- src/kernel.h
- src/names.c
Fixed to not trigger to report an error when ipv6 RA is not available
or the received RA disables dhcp while mode is set to auto, but to
deliver a 'deferred' results.
> dhcp6: differentiated mode=auto resolving from RA (bsc#1150183)

- src/dhcp6/protocol.c
Permit to assume that the address prefix-length override
specified in the config is a valid on-link prefix length,
to let the kernel create a route for this prefix.
> dhcp6: omit noprefixroute with address-length (bsc#1150972)

- configure.ac
- wicked.spec.in
Summary:
- Ship libwicked inside wicked rpm rather than as a separate sub-package
- Prevent library versioning from causing a crash when allowing (wrongly) to use an incompatible .so
> libwicked: fix versioning and packaging (bsc#1143182,bsc#1132977)

- client/Makefile.am
- client/dracut/Makefile.am
- client/dracut/cmdline.c
- client/dracut/cmdline.h
- client/dracut/dracut.c
- client/dracut/dracut.h
- client/main.c
- client/read-config.c
- configure.ac
This pull request adds initial support for parsing dracut's cmdline format so that wicked may be used to configure the network during the initramfs phase.
> dracut: expose cmdlines as config backend options

- client/main.c
- src/auto6.c
- src/buffer.c
- src/config.c
- src/dbus-objects/misc.c
- src/dbus-xml.c
- src/dhcp4/fsm.c
- src/dhcp6/protocol.c
- src/fsm.c
- src/iaid.c
- src/macvlan.c
- src/names.c
- src/netinfo_priv.h
- src/process.c
- src/route.c
- src/timer.c
- src/update.c
- src/util.c
Fix a bunch of issues found through fuzzing and static analysis. Most should be self-explanatory.
The UAFs may sound bad at first, but can't be triggered by attackers according to my best judgement.
The weirder things are probably the fixes for undefined behavior: the standard is quite stupid there, but `memcpy` may not be called with a `NULL` parameter even if the length is `0`.
The most controversial change are probably those about alignment. I believe they are correct because the buffer API gives no alignment guarantees. However, in my fuzzer I initialized these buffers with memory that wasn't aligned to those types. It's quite possible that the buffers used by the actual network code are aligned in practice (thanks to malloc's alignment guarantees). If only for robustness reasons, I …
> misc. bug fixes

- etc/systemd/wickedd-auto4.service.in
- etc/systemd/wickedd-dhcp4.service.in
- etc/systemd/wickedd-dhcp6.service.in
- etc/systemd/wickedd-nanny.service.in
- etc/systemd/wickedd.service.in
Order wickedd After Open vSwitch on startup
Otherwise these are treading on each other while bringing up interfaces
which results in failures. Ordering Open vSwitch Before network.service
isn't suficient as wickedd and wickedd-nanny may start before that.
Fixes #822
---
Order After network-pre on startup
Add network-pre.target where ordering is already After
SuSEfirewall2_init.service.
SuSEfirewall2_init.service is also missing a Before on network-pre.
After that is done in SuSEfirewall2 it can be removed here.
Quote about network-pre from man systemd.special:
This passive target unit may be pulled in by services that want to run
before any network is set up, for example for the purpose of setting up
a firewall. All network management software orders itself after this
target, but does not …
> Fixes for startup order with systemd

- wicked.spec.in
On OBS/openSUSE this has the positive side-effect of using the -mini
flavors, meaning we can move up in fhe build queue and not be
blocked behind the 'full featured systemd package'. There is no
difference for the consumers.
> Packaging: BuildRequire pkgconfig(libsystemd) instead of systemd-devel

- .editorconfig
- .gitignore
Convenient way to have project based editor config, see http://EditorConfig.org
I walked through the project and tried to identify the most common used
ways for different file types.
Following four types:
* xml and .conf files
=> 2 spaces
* manpages
=> 3 spaces
* doc/html
=> 1 space
* all others
=> tab with 8
> Introduce .editorconfig file

- src/util.c
The change to reject NULL var array names in wicked-0.6.61 (commit bfb763c) caused a  regression with default duid map file handling, e.g. `wicked duid dump` does not show the default duid any more.
> utils: don't reject NULL var array names/keys

- client/compat.c
- client/suse/compat-suse.c
- schema/interface.xml
Two issues prevent the `rto_min` value from being applied on a route when following the `ip route` syntax, e.g.:
`ip route add 172.22.151.0/24 via 172.22.99.3 dev enp1s0 rto_min 20ms`
which in our `ifroute-xxx` syntax means:
```
localhost:~ # cat /etc/sysconfig/network/ifroute-enp8s0 
default	172.22.100.1	-	-	rto_min 20ms
```
1) we expect `rto_min` value to be an int, so the `ms` (as in the default `ip` syntax) causes that it doesn't get read correctly.
2) when it is just the numeric value, we parse it and store it in our schema as `rto-min`. In our dbus layer, before sending it to the kernel, we instead attempt to load `rto_min`, resulting in the setting never being applied.
This PR fixes the latter.
> schema: change rto_min key to avoid not applying it (bsc#1160939)

- .gitlab-ci.yml
Add .gitlab-ci.yml file for GitLab CI automation through includes. This should have no effect on our GitHub repo.
> gitlab-ci: load external templates for CI

- src/util.c
Introduced in commit bfb763cfab73823b05462dd2cc9864c381925ee1, AFAIS, it's not used anywhere yet.
> utils: fix var array insert at pos < array count

- schema/team.xml
Schema defines that `hwaddr-policy` is where we store `TEAM_AB_HWADDR_POLICY` but client/compat.c is using `hwaddr_policy` instead, resulting in:
`"wickedd-nanny[710]: ni_dbus_serialize_xml_dict: ignoring unknown dict element "hwaddr_policy"`
This PR fixes the schema to use hwaddr_policy as in src/dbus-objects/team.c, client/compat.c and teamd.conf(5).
> teamd: fix schema to use correct hwaddr_policy property (boo#1171234)

- client/compat.c
- client/suse/compat-suse.c
- client/suse/config/sysconfig.dhcp-wicked
- client/wicked-client.h
- dhcp4/dbus-api.c
- man/ifcfg-dhcp.5.in
- schema/addrconf.xml
- src/appconfig.h
- src/config.c
- src/dhcp4/device.c
- src/dhcp4/dhcp4.h
- src/dhcp4/tester.c
- src/dhcp6/tester.c
Overrides the DHCPv4 client-identifier type to use specified in the
wicked-config(5) `create-cid` option, the interface type specific
client-id type and compile time defaults.
Note: DHCP over Infiniband (IPoIB) mandates an rfc4361 client-id.
> dhcp4: add DHCLIENT_CREATE_CID to ifcfg (jsc#SLE-15770)

- src/ifconfig.c
This MR bsc#1174099 by allowing an ifdown to continue when the route marked for deletion was already deleted.
> Avoid incomplete ifdown/timeout on route deletion error (bsc#1174099)

- client/ifreload.c
Check if config of currently enslaved interfaces changed also in `wicked ifreload brX` to reload (shutdown) slaves without config and removed from the slave/port list.
> ifreload: check running slaves on master reload (bsc#1168155,bsc#1172082)

- client/suse/compat-suse.c
When nsna_ping link watcher is used, we have to enable IPv6 on the ports, as this mechanism uses IPv6 ND protocol. This PR takes care of that.
> team: add IPv6 to teamd ports when nsna_ping linkwatch is used (bsc#959556)

- include/wicked/dbus.h
- src/dbus-common.c
- src/dbus-message.c
A dbus variant container with inner (typed) variant is required for migration to wpa_supplicant WPA1 dbus API.
> dbus: add initial variant container type handling

- wicked.spec.in
The old provides is kept for compatibility for now.
On a related note, `Requires(pre): %name` looks wrong here. It means that `wicked` can be removed while `wicked-service` is still happily installed.
> Let wicked-service also provide service(network)

- client/suse/compat-suse.c
The files in sysconfig directories are often prefixed with numbers to indicate an order. Presently, wicked ignores that order and so some settings that are expected to be applied last may be applied early and then overriden (e.g. by some default).
This PR adds sorting to the list of sysconfig files, fixes bsc#1181186.
> client: parse sysctl files in the correct order (bsc#1181186)

- wicked.spec.in
In order to prepare for Tumbleweed to finish the [UsrMerge](https://en.opensuse.org/openSUSE:Usr_merge), the compat symlinks in /(s)bin have to get out of the way. The rpm macro %usrmerged was introduced to allow to prepare packages and to be able to do the switch globally once as soon as all packages are prepared.
> prepare usrmerge (boo#1029961)

- src/dbus-xml.c
If a enum value contain unknown things, the error message should output
also the element name which it belongs to.
New output format looks like:
```
Dec 04 13:57:54 linux-22ob wickedd-nanny[3372]: /run/wicked/nanny/policy__wlan1.xml:21: element <auth-proto>: unknown enum value "wpa1,wpa2"
```
>  dbus: Display element name on unknown enum value error

- include/wicked/addrconf.h
- include/wicked/address.h
- src/address.c
- src/dbus-objects/addrconf.c
- src/dhcp6/device.c
- src/dhcp6/dhcp6.h
- src/dhcp6/fsm.c
- src/ifconfig.c
- src/netinfo.c
Re-trigger duplicate address detection when we may have moved to a new link, but skip it on
normal lifetime update / renew when it has been already performed (RFC8415, 18.2.10.1) to
not cause 1s packet loss during the detection.
> ifconfig: differentiate if to re-trigger dad on address updates (bsc#1177215)

- include/wicked/dbus.h
- src/dbus-common.c
- src/dbus-common.h
- src/dbus-message.c
This allow sending and receiving of DBus types like 'au'
(DBUS_TYPE_ARRAY_AS_STRING DBUS_TYPE_UINT32_AS_STRING).
Also adding some common signature utility macros and a check something to check for object_path_array.
> dbus: Add ni_dbus_variant_t of type UINT32_ARRAY

- include/wicked/dbus-service.h
- include/wicked/util.h
- src/dbus-object.c
- src/util.c
This add a generic property handling for the DBus type `ab` (ByteArray), the macro is `NI_DBUS_GENERIC_BYTE_ARRAY_PROPERTY`. It will be mapped to the generic `ni_byte_array_t` type.
The type `ni_byte_array_t` is added with all needed utility functions like new, init, destroy, free, size and put[sb].
> [dbus] Add generic property for `byte_array`

- src/xml-schema.c
We do not allow anon types in `union` or `struct`, as we already to with
`dict`.
This is forbidden after this commit:
```xml
<define name="certificate" class="union" switch="type">
<path type="string"/>
<external-file/>
<hex-string/>
</define>
```
Each child element of a union or a struct need to be defined in the
"complex" way like:
```xml
<define name="certificate" class="union" switch="type">
<path type="string"/>
<file type="external-file"/>
<hex  type="hex-string"/>
</define>
```
---
Also make the `ni_xs_name_type_array_find_local()` a bit more robust for anon types!
> xml-schema: Do not allow anon types for union and struct

- src/dhcp4/device.c
- src/dhcp4/dhcp4.h
- src/dhcp4/fsm.c
When enabled, randomize start delay in range 1..config, max 10sec.
> dhcp4: discover on reboot timeout after start-delay (bsc#1181812)

- include/wicked/util.h
- src/util.c
- testing/Makefile.am
- testing/bitmap-test.c
Add bitmap utility functions:
* `ni_parse_bitmap_array()`
* `ni_parse_bitmap_string()`
* `ni_format_bitmap_array()`
* `ni_format_bitmap_string()`
> utils: format/parse bitmap to array and string alternatives

- schema/types.xml
- src/dbus-xml.c
On XML, the data is in the format of `^([0-9a-f]{2})*$` and each two ascii
characters representing one byte.
It can be used to store opaque data in XML. The DBus end will get a
byte-array.
> xml-schema: add hex-string byte-array notation

- nanny/nanny.c
The function is calling it self recursively with `node->parent`, but
didn't checked if node is already a root one.
This just fix the `Segmentation fault` which was discovered, if we reach
a configuration constraint like:
```xml
<password type="string" constraint="required">
<meta:user-input type="password" prompt="please enter WPA EAP password"/>
</password>
```
and the password wasn't set in the current configuration.
But it doesn't fix the prompt for password!
> nanny: Fix ni_nanny_identify_node_owner() exit condition

- client/compat.c
- client/dracut/cmdline.c
- client/suse/compat-suse.c
- fix to avoid adding interface configs twice
- fix vlan id parsing from vlan interface name in dracut and also in ifcfg
- fix swapped devices, missed lowerdev config relation and improve vlan= (error) option handling
- improve bridge=, bond=, team= option (error) handling, use master relation instead port list (deprecated)
- do not generate config from `ifname=`, but expose the match as pre-parsed parser backend meta option
- refactor to parse parameters in order (e.g. bonding= before ip=)
> dracut: fix and improve option handling the cmdline parser (boo#1182227)

- extensions/firewall
Before this change, restarting the firewalld service resulted in lack of
interface assignment. This change fixes that by making the assignment
permanent.
Signed-off-by: Michal Rostecki <mrostecki@opensuse.org>
> firewalld: Make the firewalld zone assignment permanent (boo#1189560)

- src/iflist.c
With wireless we have the case, that the interface is in operstate equal
to DORMANT. This is used to indicate the EAP authentication and set by
the wpa_supplicant. In such state, we have LOWER_UP and UP, but __not__
RUNNING.
> ifstatus: Don't show link as "up", if UP and LOWER_UP but not RUNNING

- wicked.spec.in
As a system service, wicked should install the bus config in
/usr/share/dbus-1/system.d instead in /etc/dbus-1/system.d
on more recent SUSE systems. Guarded to >= 15.5 code base
as in jsc#SLE-9750, that is effective on Tumbleweed now.
> dbus: install config in /usr (bsc#1183407,jsc#SLE-9750)

- wicked.spec.in
%config is only needed when the file is installed to /etc
It shouldn't be used when it is installed to /usr
> dbus: config in /usr shouldn't be marked as %config

- src/ifevent.c
- src/iflist.c
- src/netinfo_priv.h
Do not log warnings for a valid flag combination on interface state
changes, regression of 9970c28 .
>  ifstatus: Fix warning of unexpected interface flag combination (bsc#1192164)

- client/compat.c
- client/suse/compat-suse.c
- include/wicked/wireless.h
- src/wireless.c
- src/wpa-supplicant.c
- src/wpa-supplicant.h
When wpa_supplicant get restarted (e.g. in case of an update) the previous configuration is lost.
As we configure wpa_supplicant via DBus, there is no persistent state by default, thus we need to send the 
configuration again, once wpa_supplicant is back on the DBus.
Bug: https://bugzilla.suse.com/show_bug.cgi?id=1183495
> wireless: reconnect on unexpected wpa_supplicant restart (bsc#1183495)

- client/compat.c
- client/suse/compat-suse.c
- client/suse/config/sysconfig.dhcp-wicked
- client/wicked-client.h
- dhcp4/dbus-api.c
- man/ifcfg-dhcp.5.in
- schema/addrconf.xml
- src/dhcp4/device.c
- src/dhcp4/dhcp4.h
- src/dhcp4/fsm.c
When enabled in SUSE ifcfg config files with DHCLIENT_ROUTE_SET_SRC=yes
or via `<ipv4:dhcp><route-set-src>true</route-set-src></ipv4:dhcp>` in xml
config, the DHCPv4 IP address is set as the preferred source in DHCPv4 provided
routes.
> dhcp4: add option to set route pref-src to dhcp IP (bsc#1192353)

- client/suse/compat-suse.c
- src/ipv6.c
- Discard config requests on sysctl variables which have the value "-1" (bsc#1181163, bsc#1178357)
- Do not inherit "default" and "all" settings for loopback device (bsc#1181163)
> Fix sysctl values for loopback device (bsc#1181163, bsc#1178357)

- client/suse/compat-suse.c
- client/suse/ifsysctl.c
- include/wicked/util.h
- src/util.c
* Respect sort order of filenames from sysctl.d directories (complete commit 140a945645a1292d4bb5efd240f02f386ae70ae6).
* Display sysctl key value pairs in debug
* Add `ni_var_array_sort()` function.
> Fix sysctl file read precedence

- src/fsm.c
Reset worker config instead to reject a NULL/empty config
node -- introduced in wicked 0.6.67 by commit c2a0385.
> fsm: fix device rename via yast (bsc#1194392)

- .gitlab-ci.yml
Use the wicked-ci.yml from the same `PROJECT_NAMESPACE` as the wicked
repo belongs to. E.g. if the CI is running on the project `cfconrad/wicked`
it will also use the `wicked-ci.yml` from `cfconrad/wicked-ci`.
> gitlab-ci: Use CI_PROJECT_NAMESPACE for wicked-ci

- client/suse/compat-suse.c
Previously the value of sysctl addr_gen_mode was internally set to
the value of use_tempaddr.
> compat-suse: Fix reading of sysctl varialbe addr_gen_mode

- src/auto6.c
On ifdown, the call `ni_auto6_release()` set the `auto6->enabled` state
to FALSE. This state is never changed to TRUE even if we do a explicit
`ni_auto6_acquire()`.
> Fix: Apply DNS from RA rdnss after interface ifdown/ifup (bsc#1181429)

- src/buffer.c
- src/buffer.h
- src/dhcp4/fsm.c
- src/dhcp4/protocol.c
- src/dhcp6/protocol.c
- src/firmware.c
- src/lldp.c
- adjust unsigned int buffer count and tailroom return type to size_t
- add guards and return status in init and ensure_tailroom functions
- adopt the using side to use size_t and zu printf formats
> buffer: adjust uint length to size_t, guard init

- client/suse/compat-suse.c
Match the read order of sysctl.d directories like systemd-sysctl.
progps-ng does this since 3.3.17 [1].
[1] https://gitlab.com/procps-ng/procps/-/commit/5da3024e4e4231561d922ad356a22c0d5d7bc69f
> compat-suse: Match sysctl.d read order with systemd-sysctl

- src/xml-schema.c
If the loaded xml-schema is errournous (e.g. a typo or missing include),
the cleanup can hit a ni_assert(), because of missing refcount increment
of the "array-element" type referenced in "array" type.
> xml-schema: Fix refcount handling for ni_xs_type_t

- INSTALL
- README
- configure.ac
- src/iflist.c
- src/kernel.c
- src/kernel.h
- wicked.spec.in
Remove libiw dependency (since https://github.com/openSUSE/wicked/pull/872)
used to detect wireless interfaces only.
Unfortunately `rtnetlink(7)` does not provide this info in the `NEWLINK`
message, so we're using sysfs telling us if an interface has a wireless
extension, once the `/sys/class/net/$name/wireless` directory exists
(issue: https://github.com/openSUSE/wicked/issues/910).
> wireless: remove libiw dependency

- etc/systemd/wickedd.service.in
According to udevadm systemd-udev-settle.service is deprecated. Hence removed from Wants and and After
> Remove systemd-udev-settle

- src/ifevent.c
The used `ni_socket_release()`, while restart on rtnetlink event
errors, didn't closed and deactivated/removed the obsolete socket
from poll processing immediately. This caused further restarts and
finally an assertion due to incorrect reference count (bsc#1192508).
> ifevent: always close old rtnl event sock on restart

- src/dbus-object.c
We missed the cleanup of the old value. This lead into
orphan entries in our local datastructure.
It was detected when debugging BSS info on wireless.
If I kept the same SSID/BSSID, but changed pairwise or key management
settings, the old values where still displayed. Because the dbus
object just get updated.
> dbus: Fix common dbus string_array handling

- client/ifdown.c
- client/ifreload.c
- client/ifup.c
- client/suse/scripts/ifup.in
- dhcp4/dbus-api.c
- dhcp6/dbus-api.c
- include/wicked/dbus.h
- include/wicked/fsm.h
- man/ifup.8.in
- man/wicked.8.in
- schema/addrconf.xml
- src/dbus-objects/addrconf.c
- src/dbus-xml.c
- src/dhcp4/device.c
- src/dhcp4/dhcp4.h
- src/dhcp6/device.c
- src/dhcp6/dhcp6.h
- src/fsm.c
Add `wicked <ifdown|ifreload> --[no-]release ..` option, that overrides the configured
release behavior previously applied by ifup and force to (not) release dhcp leases.
> client: add --[no-]release option to ifdown/ifreload (jsc#SLE-10249)

- .gitignore
- src/dbus-connection.c
- src/socket.c
- testing/Makefile.am
- testing/socket-mock-test.c
- testing/wunit.h
This PR is the second outcome of (bsc#1192508) and the continues work started with 
https://github.com/openSUSE/wicked/pull/912 . 
The `src/socket.c` module had some possible issues in special cases, which solved with
these changes. To avoid regressions, I created a unit test suit for that module, which show the issues in
the old implementation.
Also some code cleanup in dbus was added, where we had wrong refcount handling of `ni_socket_t` objects.
> socket.c improvements and unit tests

- src/xpath-fmt.c
If we try to format an empty node with xpath, we got a segfault
in the corresponding printf call, e.g.
```
echo "<foo><bar></bar><foo>" | \
wicked xpath --reference '/foo' '%{bar}'
```
> xpath-fmt: Fix segfault when formating an empty node

- src/iflist.c
If we process the ifinfomsg_linktype, but the interface was renamed
in the meantime, the corresponding sysfs path doesn't exists
anymore. Minimize the race possibility by requesting the new ifname.
> wireless: minimize extension/type detection race on ifrename

- src/dhcp6/fsm.c
USGv6: DHCPv6_1_2_07e,1_3_03, According to RFC 3315 Section 18.1.8,
”When the client receives a valid Reply message in response to a Release
message, the client considers the Release event completed, regardless
of the Status Code option(s)returned by the server.”
> dhcp6: consider relese complete regardless of status

- client/suse/compat-suse.c
- include/wicked/wireless.h
- src/wireless.c
- util/mkconst.c
The variable `WIRELESS_WPA_PROTO`, the field `<auth-proto>` and the capability
field `<wpa-protocols>` referencing all the same bitmap. And we would
like to see wpa/rsn instead of wpa1/wpa2.
For backward compatibility wpa1/wpa2 can still be used but
is not generated on converting ifcfg to XML.
> wireless: <auth-proto> prefer wpa/rsn values over wpa1/wpa2

- etc/Makefile.am
- etc/server.xml.in
- extensions/firewall
Reference: bsc#1201053
If a interface configuration contains FIREWALL=no, wicked should not
touch the firewall configuration on firewallUp _and_ firewallDown.
The firewall schema contains a `skip-unless-present="true"` for the
method firewallUp. This avoid the calling of the firewallUp DBus method
on the specific state, as long as the configuration doesn't contain the
<firewall> node.
On firewallDown, we do not have the configuration, thus we cannot use
`skip-unless-present="true"` here. And the firewallDown state calls
the firewallDown DBus method regardless of FIREWALL configuration value.
To avoid unexpected firewall changes, the firewall extension handle
firewallDown events only, if a corresponding firewallUp event was
invoked before.
> firewall-ext: skip firewallDown action without previous firewallUp

- client/compat.c
- client/suse/compat-suse.c
- client/wicked-client.h
The xml configuration of the slave missed
the `<link>` configuration, when generated from
ifcfg format.
> compat-team: Set <link> node in slaves (bsc#1200505)

- src/wireless.c
- src/wpa-supplicant.c
- src/wpa-supplicant.h
Once wpa_supplicant restart unexpected, wickedd tend to crash, if the wpa_supplicant handler code was currently in one of the
DBus calls. To fix this, we need refcounting for the DBus objects of wpa_supplicant and be aware of such a situation in error handing.
> wpa_supplicant: Fix crash on unexpected restarts of wpa_supplicant

- etc/Makefile.am
- etc/server.xml.in
- extensions/firewall
Do not change firewalld settings on ifdown, neither for FIREWALL=yes
nor for FIREWALL=no (bsc#1201053 and bsc#118950).
The problem is, that `firewall-cmd --permanent` also change ifcfg
files, thus it would remove the ZONE= setting from ifcfg on ifdown.
Changing only runtime firewall settings, trigger a unexpected
inconsistency between runtime+persistent config.
> firewall-ext: Do not change firewalld setting on ifdown

- testing/bitmap-test.c
Maps are supposed to end with a NULL element as otherwise out of bounds reads can occur.
> testing: Null terminate map in bitmap-test

- client/compat.c
- client/suse/compat-suse.c
- client/suse/config/sysconfig.dhcp-wicked
- client/wicked-client.h
- dhcp6/dbus-api.c
- man/ifcfg-dhcp.5.in
- schema/addrconf.xml
- src/dhcp6/device.c
- src/dhcp6/dhcp6.h
- src/dhcp6/fsm.c
Add config option to refresh a lease with (managed) IP address using
a rebind (like when it would contain a prefix) instead to confirm if it's
appropriate to the link only (jsc#SLE-9492,jsc#SLE-24307).
> dhcp6: add option to refresh lease instead to confirm it

- schema/interface.xml
Trying to create a static rule by creating /etc/sysconfig/network/ifrule-eth0 with
```
ipv4 from 1.2.3.4 to 3.4.5.6 priority 4 table main
```
does not work; the interface never comes up. wickedd-nanny says:
```
Nov 14 14:58:48 host-abc wickedd-nanny[947]: <buffer>:30: cannot parse array with notation "net-address", value="2.3.4.5/32"
Nov 14 14:58:48 host-abc wickedd-nanny[947]: device eth0: interface document error
Nov 14 14:58:48 host-abc wickedd-nanny[947]: eth0: failed to bring up device, still continuing
```
This change and a restart of wickedd fixes the issue. It also works when specifying a /24 (as an example).
> schema: Make the rule to-selector handle network prefixes

- wicked.spec.in
Add /etc/sysconfig/network to file list of wicked-service sub package to fix build failures with cleaned up filesystem package.
> Add /etc/sysconfig/network to file list

- client/ifstatus.c
- include/wicked/constants.h
Split the transient `setup-in-progress` status and show `no-carrier` status
when the interface is set administratively up (device-up), but the (L2)
link is not up and running yet (link-up), including e.g. not-associated
wireless links. The following (L3) setup like IP / lease acquisition
continues to appear as setup-in-progress until the setup is sufficient
and we consider the interface it as up.
> ifstatus: improve to show a no-carrier status

- nanny/policy.c
Fix a use-after-free by getting a local mpolicy->fsm_policy reference in unregister_managed_policy to safely access the fsm policy name for a debug message logged after unregistering the mpolicy object, which is freeing the mpolicy (if it's the last reference).
A policy deletion is performed by wicked ifdown or ifreload and the execution is limited to root (uid 0) callers, so it does not bring additional privilege possibilities.
> nanny: fix use-after-free in debug mode (bsc#1206447)

- client/Makefile.am
- client/firmware.c
- client/main.c
- client/main.h
- client/read-config.c
- client/read-config.h
- include/wicked/netinfo.h
- src/Makefile.am
- src/firmware.c
- src/firmware.h
- `wicked firmware extensions` shows available firmware extensions table:
```
ibft          enabled
redfish       enabled
```
- `wicked firmware interfaces` shows interfaces configured by a firmware:
```
ibft          eth1 eth1.10
redfish       usb0
```
See also https://github.com/openSUSE/installation-images/pull/620
> client: add firmware extensions|interfaces command (jsc#PED-3132)

- src/ifconfig.c
The kernel bonding accepts only enslave of interfaces in DOWN state and the bonding driver sets the slave UP itself after enslave, once it also inherited MTU, MAC address, ... to the slave as needed.
All kernels between (at least) 4.12 up to 6.0 accepted to enslave using a single `ip link set down master bond0 dev eth0` rtnetlink message, which ensured that the (eth0) interface to enslave were set down if needed and wasn't rejected to enslave.
Since kernel 6.1 (commit a4abfa627c3865c37e036bccb681619a50d3d93c) the enslave processing changed and the `down` flag in the enslave message is applied after enslave, causing that the UP flag added by enslave is removed again, the slave remains inactive and is not used by the bond, which remains in a no-carrier state.
Changed to not pass the DOWN …
> bond: workaround 6.1 enslave regression (boo#1206674)

- include/wicked/addrconf.h
- include/wicked/address.h
- include/wicked/refcount.h
- include/wicked/route.h
- include/wicked/wireless.h
- src/Makefile.am
- src/addrconf.c
- src/address.c
- src/refcount.c
- src/refcount_priv.h
- src/route.c
- src/wireless.c
- src/wpa-supplicant.c
- src/wpa-supplicant.h
Changed to use ni_declare|ni_define as prefix
and split declaration and definition macros.
> refcount: split declaration and definition macros

- autogen.sh
- Add `-Werror` option to fail on compiler warnings and `-debug0` for non-optimized
build (`-g -O0` plus) for an intended gdb use.
- Enable silent-rules to improve warnings/issues visibility in favor of full libtool output
and pass all other options to configure additionally and not instead of our defaults,
now considering also _rundir rpm config.
> autogen.sh: improve usability and enable silent rules

- configure.ac
- etc/Makefile.am
- extensions/Makefile.am
- wicked.spec.in
Add rpmbuild --with[out] nbft conditional along with the configure --disable-nbft option
to not build the wicked-nbft firmware extension rpm sub-package on SLE/LEAP < 15.5.
> wicked-nbft: conditionally disable on SLE < 15-SP5

- client/suse/compat-suse.c
Do not read `WIRELESS_EAP_AUTH` when `WIRELESS_EAP_MODE=TLS` is used.
> wireless-ifcfg: Ignore WIRELESS_EAP_AUTH within TLS (bsc#1211026)

- configure.ac
- src/json.c
- src/json.h
- testing/json-test.c
- add basic indenting support to format_string and file parsing utility
- enable iconv to unescape (paired and unpaired UTF-16) unicode sequences
> json: improve parsing and add basic indenting

- extensions/nbft
- testing/nbft/dhcp-routed/nbft.out
- testing/nbft/dhcp-simple/nbft.out
- testing/nbft/dhcp-vlan/nbft.out
- testing/nbft/static-bad-gateway/nbft.out
- testing/nbft/static-no-prefix/nbft.out
- testing/nbft/static-routed-vlan/nbft.out
- testing/nbft/static-routed/nbft.out
- testing/nbft/static-vlan/nbft.out
In multipath scenarios, not all NBFT interfaces and respective connections may have been brought up during initramfs processing. If wicked brings up some NBFT interfaces after switching to the root file system, run a post-up script to initiate the NVMe connections.
> extensions/nbft: add post-up script (bsc#1211647)

- src/array_priv.h
- src/route.c
- src/wireless.c
- testing/ptr_array-test.c
Add macro to define qsort element compare wrapper in favour
of a nested wrapper inside the array qsort function to avoid
executable stack requirements.
> array: add macro to define qsort cmp function

- configure.ac
- testing/Makefile.am
Execute nbft-test.sh in make check only when nbft
is enabled and also the jq utility is available.
> testing: run nbft-test.sh only if jq is available

- autoip4/autoip.h
- autoip4/fsm.c
- client/arputil.c
- include/wicked/time.h
- man/wicked-config.5.in
- src/addrconf.h
- src/appconfig.c
- src/appconfig.h
- src/arp.c
- src/dhcp4/dhcp4.h
- src/dhcp4/fsm.c
- src/ifconfig.c
- src/netinfo_priv.h
- src/timer.c
* Read probe and notify settings from config file
* Retry arp verify/notify on ENOBUFS
* Unify arp verify/notify in autoip4, dhcp4 and static-ip
* client: allow interval as range for `wicked arp verify`
>  arp: Improve error handling and default settings 

- src/appconfig.c
- src/arp.c
- src/ifconfig.c
- src/netinfo_priv.h
* fix the regression [boo#1212806](https://bugzilla.suse.com/show_bug.cgi?id=1212806) introduced with https://github.com/openSUSE/wicked/pull/979 
* fix the burst sending of max 256 arp verify/notify messages
* config value of `<arp><verify|notify><count>` need to be greater then `0`
> ifconfig: fix arp notify loop (boo#1212806) and burst sending

- src/appconfig.c
- src/extension.c
In ni_system_updaters_init(), the updater's format is set by using ni_updater_format_type(ex->format). This in turn is used by ni_system_updater_generic_leaseinfo_create(), which is called by ni_system_updater_generic_install_call(). As ex->format is never actually set, ni_system_updater_generic_leaseinfo_create will always fail with an unknown format error and the install call is never executed.
> system-updater: Parse updater format from XML configuration to ensure install calls can run.

- src/ifevent.c
- src/iflist.c
- src/kernel.h
Due to the incomplete parsing the peer address were empty
and caused an error in attempts to delete it while ifdown.
> rtnl: parse peer address on non-ptp interfaces

- src/duid.h
v6time is seconds since midnight (UTC), January 1, 2000, modulo 2^32. The value is generated correctly but the comment refers to 2001 instead of 2000.
> duid: fix comment for v6time

- client/ifstatus.c
- client/suse/scripts/ifup.in
The 'no-carrier' status was separated from the 'setup-in-progress' status. Even though the interface appears active during this status, the setup process is not complete and the NIC is not ready. Therefore, the `ifstatus <nic>` command should not return 0 for this status.
> client: fix exit code for no-carrier status (bsc#1219265)

- client/ifcheck.c
This fix the outcome of the following commands:
```bash
source /etc/sysconfig/network/ifcfg-en0
grep IPADDR /etc/sysconfig/network/ifcfg-en0
sed -i '/IPADDR/cIPADDR=10.1.2.5/24' /etc/sysconfig/network/ifcfg-en0
wicked ifcheck --changed en0 && echo "ERROR config changed not notified"
sed -i '/IPADDR/cIPADDR='$IPADDR /etc/sysconfig/network/ifcfg-en0
wicked ifcheck --changed en0 || echo "ERROR unexpected config changed"
```
> ifcheck: fix config changed check (bsc#1218926)

- src/xpath.c
We use underscores in our own XML schema. So lets allow such names in `wicked xpath --reference XXX`.
> xpath: allow underscore in node identifier

- client/ifstatus.c
- src/dbus-objects/addrconf.c
This PR fix [bsc#1220996](https://bugzilla.suse.com/show_bug.cgi?id=1220996). The issue is a wicked boot-up time increase, when using `BOOTPROTO='dhcp+autoip'` from 15s to 30s, whenever wicked got a LEASE from the DHCPv4 server.
> addrconf: fix fallback-lease drop (bsc#1220996)

- include/wicked/logging.h
- include/wicked/xml.h
- nanny/device.c
- src/firmware.c
- src/logging.c
- src/wpa-supplicant.c
- src/xml.c
Replaces cdata in a copy of a config node and it's children that contain passwords before logging it.
Please merge https://github.com/openSUSE/wicked/pull/1005 first.
> hide secrets in debug log (bsc#1221194) 

- client/ifdown.c
- src/fsm.c
Fix to not convert user-timeout in seconds into to timer timeout in millisecond twice.
It caused to wait 1000 times longer when a bridge with stp=on starts and all it's ports
are disconnected and unable to find carrier.
> client: fix to not convert sec to msec twice (bsc#1222105)

- client/ifup.c
- include/wicked/fsm.h
- nanny/nanny.c
- schema/interface.xml
- src/fsm.c
- Change schema to add ports to master in `device-up` state, so the
(bond) master has an already configured MTU and propagates it
to the ports.
- Fix to not stop monitoring non-hotplug ports or lower interfaces
when a link (vlan) on  top finished before the lower itself.
> bond: add ports when master is up (bsc#1219108)

- client/ifcheck.h
- client/ifdown.c
- client/wicked-client.h
- include/wicked/fsm.h
- include/wicked/wireless.h
- nanny/device.c
- src/client/client_state.c
- src/client/client_state.h
- src/client/ifconfig.h
- src/fsm.c
- src/modem-manager.c
- src/names.c
- src/netdev.c
- src/xml-writer.c
- testing/cstate-test.c
- Fix inconsistent function declarations with unsinged int instead of ni_fsm_state_t
- Remove unused ni_fsm_state_t state argument artefact from ni_client_state_new
- Remove __ prefix from NI_FSM_STATE_MAX enum constant.
> cleanup: fix enum-int-mismatch warnings

- autoip4/autoip.h
- autoip4/device.c
- client/ethtool.c
- client/redfish.c
- client/suse/compat-suse.c
- include/wicked/netinfo.h
- include/wicked/types.h
- src/addrconf.c
- src/auto6.c
- src/bonding.c
- src/capture.c
- src/dhcp4/device.c
- src/ethernet.c
- src/ethtool.c
- src/fsm.c
- src/icmpv6.c
- src/iflist.c
- src/netdev.c
- src/netinfo.c
- src/ovs.c
- src/ppp.c
- src/pppd.c
- src/route.c
- src/update.c
- src/wpa-supplicant.c
Added a loop guard to system and config interface worker hierarchy traversing
logged as debug or in a --dry-run and fixed resolving of link reference names
pointing to another netnsid and causing such a loop and wicked ifup crash in
systemd-nspawn containers using macvlans.
> client: fix crash in hierarchy traversing (bsc#1226664)

- client/compat.c
- client/ifstatus.c
- client/suse/compat-suse.c
- include/wicked/util.h
- include/wicked/wireless.h
- man/ifcfg-wireless.5.in
- man/src/ifcfg-wireless.5.md
- schema/wireless.xml
- src/dbus-objects/wireless.c
- src/util.c
- src/wireless.c
- src/wpa-supplicant.c
* introduce new `WIRELESS_FREQUENCY_LIST` and `<frequency-list>`
* It is possible to specify a frequency directly or use one of the following aliases `2.5GHz`, `5GHz`, `6GHz`.
* add `channel/frequency` info into `wicked ifstatus --verbose wlanX`
* add `frequency` to scan results
```bash
tw-1:~ # wicked ifstatus --verbose  wlan1
wlan1           up
link:     #6, state up, mtu 1500
type:     wireless, state established, ssid MySSID Muha, WPA2-PSK+WPA-PSK
wireless: bssid 02:00:00:00:00:00, signal -30, channel 6 (2437MHz), duration 680s
control:  none
...
```
> wireless: add frequency-list in station mode (jsc#PED-8715)

- client/ifcheck.c
- client/ifreload.c
- client/ifstatus.c
- client/ifup.c
- client/nanny.c
- client/read-config.c
- client/wicked-client.h
- src/client/policy.c
When loading and migrating a master xml configuration with
obsolete port array and missed port interface configurations,
the migration hook were unable to inherit the origin from
master configuration cleared by a "read raw config" request,
failed to apply the port configurations caused a no-carrier
setup state on the (bond) master.
> client: fix to set and use origin in loaded config (bsc#1226125)

- client/suse/compat-suse.c
Commit 98b4fb3359ebf48e2466338df2b89e263e0aa609 introduced changes causing dummy interaces configured using "INTERFACETYPE=dummy" or "DUMMY=yes" to presumably inadvertently no longer be recognized. Restore functionality of these settings by only calling the new pattern matching logic if a prior iftype lookup did not yield success. This is needed to continue supporting configuration of dummy interfaces not matching the predefined naming scheme.
The following constellations have been tested:
- "ifcfg-foo" file with "INTERFACETYPE=dummy"
- "ifcfg-foo" file with "DUMMY=yes"
- "ifcfg-dummy1" file without "INTERFACETYPE" or "DUMMY"
Fixes: 98b4fb3359eb ("compat-suse: fix dummy type detection from ifname")
Signed-off-by: Georg Pfuetzenreuter <mail@georg-pfuetzenreuter.net>
> compat-suse: repair dummy interfaces (boo#1229555)

- etc/systemd/wickedd-auto4.service.in
- etc/systemd/wickedd-dhcp4.service.in
- etc/systemd/wickedd-dhcp6.service.in
- etc/systemd/wickedd-nanny.service.in
- etc/systemd/wickedd.service.in
After the change to dbus-broker it was possible for wicked to start before the dbus-broker service was running. Adding `BindsTo: dbus.socket` fixes this.
https://bugzilla.suse.com/show_bug.cgi?id=1229745
https://bugzilla.suse.com/show_bug.cgi?id=1229799
https://bugzilla.suse.com/show_bug.cgi?id=1229800
> systemd: ensure wicked launches after dbus service

- src/dbus-common.c
In an initial `ni_dbus_array_grow` call there is no data yet and the source data pointer is restricted in `memcpy`.
> dbus: don't memcpy empty/NULL array value

- src/socket.c
We may wait for timeout only without any sockets.
> socket: avoid complaints about zero-size array

- src/arp.c
According to RFC5227 section 2.1.1, the "'target hardware address' field is ignored and SHOULD be set to all zeroes".
The section 2.3 defines that an announcement is identical, except of the announced IP in sender and target IP field.
> arp: don't set target broadcast hardware address

- client/compat.c
- man/ifcfg-team.5.in
- man/src/ifcfg-team.5.md
- src/team.c
`teamd` version `< 1.32` do not have a default value for link watch
interval. And if the configuration option is missed, the team
interface will never have any active port.
>  team: set arp link watcher interval default to 1s 

- man/wicked-config.5.in
- src/appconfig.c
- src/appconfig.h
- src/dhcp4/device.c
- src/dhcp4/dhcp4.h
- src/dhcp4/protocol.c
The RFC3927 Section 1.6: Alternate Use Prohibition prohibits the use of link-local
IPv4 (zeroconf) address range for other purposes, such as for DHCP.
Enabling this option in wicked-config(5) permits to use the addresses in DHCP.
> dhcp4: add ignore-rfc3927-1-6 wicked-config(5) option (jsc#PED-10855)

- man/wicked-config.5.in
Describe inclusion of the `local.xml` and other files intended
for custom definitions, mention to restart wickedd on changes.
> man: improve wicked-config(5) file description

- client/compat.c
- src/dbus-objects/addrconf.c
- src/dbus-objects/interface.c
- src/dbus-objects/misc.c
- src/dbus-objects/model.h
- Fix to not omit generation of route destination xml node when prefix length is 0 (default route).
- Fix to use lease family as hint for routes with missing destination in dbus dict (backward compatibility).
> route: fix family and destination processing (bsc#1231060) 

- autoip4/fsm.c
- client/dracut/cmdline.c
- client/redhat/compat-redhat.c
- client/suse/compat-suse.c
- include/wicked/route.h
- src/dbus-objects/misc.c
- src/dhcp4/protocol.c
- src/ifconfig.c
- src/leasefile.c
- src/netinfo.c
- src/route.c
- Avoid unsafe use of append(array, ref(entry)) function calls not allowing to release reference
on append failure in favor of the new append_ref(array, obj) and insert_ref macros.
- Free discarded duplicate route and route rule option array and on parse errors.
- Remove table list argument from route create for consistent reference counting behavior.
> route: use new array macros and fix on error leaks

- client/ifreload.c
- client/ifstatus.c
- client/ifup.c
- include/wicked/fsm.h
- nanny/device.c
- nanny/nanny.c
- src/fsm-policy.c
- src/fsm.c
Refactored and cleaned up to use our common refcounting and array macros
so the worker and policy are using the same function prototypes, e.g. same
names and meaning of array remove vs. delete.
> fsm: use refcount and array macros in worker and policy

- include/wicked/fsm.h
- nanny/interface.c
- src/fsm-policy.c
- src/fsm.c
The fsm worker is a structure that contains config and/or device.
Use the master/lowerdev worker config interface references only
and remove the confusing children array causing complex cleanup.
> fsm: remove children reference array from worker 

- client/compat.c
- client/convert.c
- client/dracut/cmdline.c
- client/ifdown.c
- client/ifup.c
- client/nanny.c
- client/read-config.c
- nanny/main.c
- nanny/nanny.c
- nanny/policy.c
- src/Makefile.am
- src/client/ifxml.c
- src/client/ifxml.h
- src/fsm-policy.c
- src/fsm.c
- Cleanup `is_config` and `is_policy` utilities to use `ni_ifxml` prefix,
the interface related xml configuration in the `wicked:xml` scheme.
- Fix return status and in set owner and uuid utils and use the status
when parsing `ifpolicy` xml node into an `fsm-policy` object.
- Disable the experimental and never used `template` policy type.
- Ensure the `fsm-policy` parsed from xml is complete or fail to parse.
> policy: cleanup ifxml utils and fsm policy parsing

- include/wicked/fsm.h
- include/wicked/xml.h
- nanny/device.c
- nanny/nanny.c
- nanny/policy.c
- src/client/ifxml.h
- src/fsm-policy.c
- src/xml.c
- Fix crash and leak on error in policy action processing when transforming
them to effective config (not triggered by policies generated from ifcfg).
- Cleanup applicable fsm policy matching to use fsm_policy_array in recheck
- Adjust fsm function names acting on policies vs fsm-policy functions.
- Changed to replace the inner fsm-policy in managed policy update instead
to tweak it's content, to not require content changed compare later.
> policy: cleanup fsm-policy match and transform processing
