openSUSE/wicked

src/fsm.c

in commit e4e7b06 fsm: include worker's fsm context in timer data

fsm: fixed set timeout bug introduced by pull#504

---

dhcp6/device.c

When NEWPREFIX arrives, there definitely were an RA, but
when the RA contained a RetransTimer/ReachableTime of 0
(unspecified / no change to before), the kernel forgets to
send a NEWLINK event, even other things in the RA, as
the managed/other-config flags we wait for, changed.

dhcp6: refresh ipv6 link on newprefix in auto mode (bsc#934067)

---

client/ifup.c
include/wicked/fsm.h
nanny/device.c
nanny/interface.c
nanny/nanny.c
src/fsm-policy.c
src/fsm.c

There are also some cleanup commits.

fsm, nanny and client related fixes improving handling of hotplug scenarios

---

src/ifconfig.c

In the case of standard openvswitch bridge ports, they are enslaved
by openvswitch itself to the ovs-master interface (kernel datapath
interface).
In such scenarios, we previously skipped the linkUp process, as Wicked
assumed that if a device was already enslaved, it was done via
ni_system_interface_enslave(), which generates a netlink message to
enslave and perform a link-up in bridge case, and a bonding master
manages the link state itself.
To get around this, if a device has a master, we should first check to
see if it's in link-up state. If yes, then it was enslaved by Wicked
and no furhter processing is needed. If not, then it was enslaved
externally and we need to perform the basic link-up.

ifconfig: handle link up of externally enslaved devices (fate#318840)

---

src/fsm.c

When the lower device (bond0) of the one we want to ifup (vlan1 on
bond0), has an unrelated/inactive in this ifup run, but sufficiently
configured master (br0 on bond0), continue instead to follow and
enforce link-up/enslave requirements on this unrelated master.

fsm: no link-up check on unrelated master (bsc#948423)

---

src/ifconfig.c

While the kernel does not need explicit broadcast, other code,
like the glibc getbroadcastnets() function, that requires it
and removing the calulation in bsc#944710, caused regression.

ifconfig: readd broadcast calculation (bcs#971629)

---

include/wicked/addrconf.h
src/arp.c
src/capture.c
src/config.c
src/dbus-objects/misc.c
src/dhcp4/device.c
src/dhcp4/dhcp4.h
src/dhcp4/fsm.c
src/dhcp4/lease.c
src/dhcp4/protocol.c
src/leaseinfo.c
src/lldp.c
src/netinfo_priv.h

https://github.com/openSUSE/wicked/issues/663

dhcp4: add sender hw-address to lease if available (issue#663)

---

src/dhcp6/device.c

As a workaround for a missed NEWLINK on IPv6 RA changes when RA times
are set to 0 (unspecified) by the router (bug 975020), we refresh the
ipv6 link on a newprefix event. This fix corrects the workaround added
in wicked 0.6.32, which did not catched the cases as needed.

dhcp6: fix refresh on newprefix workaround (boo#972471)

---

client/compat.c
client/suse/compat-suse.c
include/wicked/ethernet.h
schema/ethernet.xml
src/dbus-objects/ethernet.c
src/ethernet.c

ethtool: add support for parsing ethtool ring parameters(bsc#1012366, gh#openSUSE/wicked#685)

 	ethtool: handle ring parameters (bsc#1007909)

---

src/ifconfig.c

ifconfig: do not stop adding routes on one bad route (bsc#1036619)

---

client/arputil.c
client/main.h

was cause by 15e69c474b02971b63d5a177ba8bf364b2fc261c

arp: fix ni_do_arp declaration(bsc#1078245)

---

server/main.c

An additional manual refresh of interfaces and their properties to fetch ethtool settings
for ready devices after initial bootstrap of their state may cause to find further devices
just detected by the kernel without to register them on the dbus layer and cause the
event handlers taking over after, to emit device-change instead a device-create event
and thus to not register them again and finally report them as "no-device" in an ifup.

wickedd: fix netdev bootstrap race (bsc#1107579)

---

man/ifcfg-ovs-bridge.5.in

This may help avoiding user surprises.

man: ifcfg-ovs-bridge(5): recommend STARTMODE=nfsroot

---

src/dhcp4/fsm.c

dhcp4: nullify defer timer pointer when timeout

---

client/Makefile.am
client/compat.c
client/convert.c
client/main.c
client/main.h
client/nanny.c
client/read-config.c
client/read-config.h
client/wicked-client.h
src/xml.c

Also add an initial show-policy command directly generating a policy from compat

client: cleanup convert and show-config commands

---

INSTALL

Additionally to list available in INSTALL I needed this two packages on clean SLE 15 SP2 to proceed with wicked compilation

Add missing packages to INSTALL instructions

---

src/process.c

Changed the error log message to debug with an additional warning message when it took 1sec or more.

process: log command of reaped child (gh#openSUSE/wicked#741)

---

etc/client.xml.in
extensions/Makefile.am
extensions/nbft
testing/Makefile.am
testing/nbft-test.sh
testing/nbft/dhcp-broken-json-01/nbft-hfi.json
testing/nbft/dhcp-no-index/nbft-hfi.json
testing/nbft/dhcp-no-mac/nbft-hfi.json
testing/nbft/dhcp-routed/nbft-hfi.json
testing/nbft/dhcp-routed/nbft.out
testing/nbft/dhcp-simple/nbft-hfi.json
testing/nbft/dhcp-simple/nbft.out
testing/nbft/dhcp-vlan/nbft-hfi.json
testing/nbft/dhcp-vlan/nbft.out
testing/nbft/static-bad-gateway/nbft-hfi.json
testing/nbft/static-bad-gateway/nbft.out
testing/nbft/static-broken-json-01/nbft-hfi.json
testing/nbft/static-invalid-ip/nbft-hfi.json
testing/nbft/static-no-index/nbft-hfi.json
testing/nbft/static-no-mac/nbft-hfi.json
testing/nbft/static-no-prefix/nbft-hfi.json
testing/nbft/static-no-prefix/nbft.out
testing/nbft/static-routed-vlan/nbft-hfi.json
testing/nbft/static-routed-vlan/nbft.out
testing/nbft/static-routed/nbft-hfi.json
testing/nbft/static-routed/nbft.out
testing/nbft/static-vlan/nbft-hfi.json
testing/nbft/static-vlan/nbft.out

This extension imports configuration from the NBFT,
according to the NVM Express Boot Specification 1.0
and convert it to the correspondig wicked configuration.

 extensions: add nbft extension (jsc#PED-3132) 

---

.gitignore
etc/Makefile.am
etc/client-nbft.xml.in
etc/client.xml.in
wicked.spec.in

- introduced a `wicked-nbft` sub-package
- moved nbft definition to `client-nbft.xml`

nbft: introduced new wicked-nbft sub-package (jsc#PED-3132)

---

testing/wunit.h

Test result output should not exceed 80 chars per line.

testing: Improve test result formatting

---

src/arp.c
src/capture.c
src/dhcp4/protocol.c
src/lldp.c
src/netinfo_priv.h

* Resend ARP verify request on ENOBUFS error
* Improve debug and error output for capture module
* code cleanup

arp: resend DAD request on ENOBUFS (bsc#1203300)

---

include/Makefile.am
include/wicked/slist.h
src/Makefile.am
src/slist_priv.h

Add simple single-linked list declaration macros

utils: initial single-linked list utility macros

---

include/Makefile.am
include/wicked/array.h
src/Makefile.am
src/array_priv.h
testing/Makefile.am
testing/ptr_array-test.c

Implement pointer array API generated through preprocessor.

utils: add pointer array implementation macros

---

client/suse/compat-suse.c
include/wicked/ovs.h
include/wicked/route.h
include/wicked/team.h
include/wicked/wireless.h
src/dbus-objects/addrconf.c
src/dbus-objects/wireless.c
src/iflist.c
src/netinfo.c
src/ovs.c
src/route.c
src/team.c
src/wireless.c

* ni_wireless_network_array_t
* ni_route_array_t
* ni_rule_array_t
* ni_team_port_array_t
* ni_team_link_watch_array
* ni_ovs_bridge_port_array_t

Use ptr_array for current array implementations 

---

client/ifreload.c
include/Makefile.am
include/wicked/compiler.h
include/wicked/logging.h
src/duid.c
src/duid.h
src/fsm.c
testing/wunit.h

Code cleanup/preparation for logging.h changes.

Move all __attribute__ definitions to compiler.h

---

client/ifcheck.c

Also print config uuid's in debug, regardless of the result.

ifcheck: fix changed for new/del cfgs (bsc#1218926)

---

client/arputil.c

Better usability + source code readability.

 arputil: Document minimal interval for getopts

---

wicked.spec.in

Last commit in `wicked.spec.in` was on May 2024, I guess we simply forgot to update the date.

wicked.spec.in: update date to 2024

---

etc/systemd/wickedd-auto4.service.in
etc/systemd/wickedd-dhcp4.service.in
etc/systemd/wickedd-dhcp6.service.in
etc/systemd/wickedd-nanny.service.in
etc/systemd/wickedd.service.in

Fix typo in https://github.com/openSUSE/wicked/pull/1032

systemd: fix typo to use correct BindsTo=

---

src/client/policy.c

- migrate master and lower references in policy matches
- generate missing config/policy for lower interfaces
- warn when missing config has been generated

ifxml: migrate and generate lower configs/policies

---

src/client/policy.c

Follow up to:
- https://github.com/openSUSE/wicked/pull/1048
- https://github.com/openSUSE/wicked/pull/1050

ifxml: generate missing ipvlan/tap lower configs/policies
